// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../models/chapter.dart';
import '../../models/character.dart';
import '../../models/config.dart';
import '../../models/dialog.dart';
import '../../models/faq.dart';
import '../../models/level.dart';
import '../../models/question.dart';
import '../../models/type_question.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5973314585981616737),
      name: 'Chapter',
      lastPropertyId: const obx_int.IdUid(7, 7687897233266483870),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4221266939847535234),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3024027075428428312),
            name: 'refId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(1, 4272032327039726676)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7909822941811060262),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4516517381377346705),
            name: 'backgroundImgPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5828808536189333364),
            name: 'iconImgPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1662244797978207885),
            name: 'defaultDialogs',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7687897233266483870),
            name: 'characterId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 2569115553188492082),
            relationTarget: 'Character')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8572854090930341858),
      name: 'Character',
      lastPropertyId: const obx_int.IdUid(4, 4315755590890387020),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5612062901542984706),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 723683309010309965),
            name: 'refId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(3, 4640869521664756704)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6453527414324211765),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4315755590890387020),
            name: 'pathImg',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 8408800768045639856),
      name: 'Config',
      lastPropertyId: const obx_int.IdUid(3, 8717339309125641126),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 475070841385780781),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6187491828509691819),
            name: 'username',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8717339309125641126),
            name: 'insertedTables',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3406974681540967323),
      name: 'Dialog',
      lastPropertyId: const obx_int.IdUid(4, 5798856795710583153),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7621568563904688952),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3651909786407415004),
            name: 'refId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(4, 2776218141814564241)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6055467020363662882),
            name: 'texts',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5798856795710583153),
            name: 'characterId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 3585966396648816082),
            relationTarget: 'Character')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4852888588560463239),
      name: 'Faq',
      lastPropertyId: const obx_int.IdUid(6, 8838459757260935310),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3625968654843321966),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9028145453339080403),
            name: 'refId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(6, 6055474899643521103)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7828140111856259721),
            name: 'question',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4337080072963131235),
            name: 'answer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4821108454246175467),
            name: 'embedding',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(7, 1040314439887357833),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 384,
            )),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8838459757260935310),
            name: 'chapterId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 3431805966167694409),
            relationTarget: 'Chapter')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 6658781409194574519),
      name: 'Level',
      lastPropertyId: const obx_int.IdUid(7, 6714547495560024784),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1779490834382340472),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1869606200134161179),
            name: 'refId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(9, 2634038929821472341)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 500761637304787835),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1813659786784187015),
            name: 'position',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2291635270235067726),
            name: 'dataLevel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 981069108101036886),
            name: 'isCompleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6714547495560024784),
            name: 'chapterId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(10, 2889916965937761177),
            relationTarget: 'Chapter')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 472936416562774771),
      name: 'Question',
      lastPropertyId: const obx_int.IdUid(5, 7683046944203301860),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3906966699697460699),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6130157587554444537),
            name: 'refId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(11, 6103568268844684949)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1637340321130407071),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1065319458034757365),
            name: 'dataQuestion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7683046944203301860),
            name: 'typeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(12, 362384957612295319),
            relationTarget: 'TypeQuestion')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 1949517125018412760),
      name: 'TypeQuestion',
      lastPropertyId: const obx_int.IdUid(3, 3255603231274766490),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6581646779562970523),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8858650155636454094),
            name: 'refId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(13, 3643538127318295405)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3255603231274766490),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(8, 1949517125018412760),
      lastIndexId: const obx_int.IdUid(13, 3643538127318295405),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Chapter: obx_int.EntityDefinition<Chapter>(
        model: _entities[0],
        toOneRelations: (Chapter object) => [object.character],
        toManyRelations: (Chapter object) => {},
        getId: (Chapter object) => object.id,
        setId: (Chapter object, int id) {
          object.id = id;
        },
        objectToFB: (Chapter object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final backgroundImgPathOffset =
              fbb.writeString(object.backgroundImgPath);
          final iconImgPathOffset = fbb.writeString(object.iconImgPath);
          final defaultDialogsOffset = fbb.writeList(object.defaultDialogs
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.refId);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, backgroundImgPathOffset);
          fbb.addOffset(4, iconImgPathOffset);
          fbb.addOffset(5, defaultDialogsOffset);
          fbb.addInt64(6, object.character.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final backgroundImgPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final iconImgPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final defaultDialogsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 14, []);
          final object = Chapter(
              refId: refIdParam,
              name: nameParam,
              backgroundImgPath: backgroundImgPathParam,
              iconImgPath: iconImgPathParam,
              defaultDialogs: defaultDialogsParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.character.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.character.attach(store);
          return object;
        }),
    Character: obx_int.EntityDefinition<Character>(
        model: _entities[1],
        toOneRelations: (Character object) => [],
        toManyRelations: (Character object) => {},
        getId: (Character object) => object.id,
        setId: (Character object, int id) {
          object.id = id;
        },
        objectToFB: (Character object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final pathImgOffset = fbb.writeString(object.pathImg);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.refId);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, pathImgOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final pathImgParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = Character(
              refId: refIdParam, name: nameParam, pathImg: pathImgParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Config: obx_int.EntityDefinition<Config>(
        model: _entities[2],
        toOneRelations: (Config object) => [],
        toManyRelations: (Config object) => {},
        getId: (Config object) => object.id,
        setId: (Config object, int id) {
          object.id = id;
        },
        objectToFB: (Config object, fb.Builder fbb) {
          final usernameOffset = fbb.writeString(object.username);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, usernameOffset);
          fbb.addBool(2, object.insertedTables);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final usernameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Config(username: usernameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..insertedTables =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);

          return object;
        }),
    Dialog: obx_int.EntityDefinition<Dialog>(
        model: _entities[3],
        toOneRelations: (Dialog object) => [object.character],
        toManyRelations: (Dialog object) => {},
        getId: (Dialog object) => object.id,
        setId: (Dialog object, int id) {
          object.id = id;
        },
        objectToFB: (Dialog object, fb.Builder fbb) {
          final textsOffset = fbb.writeList(
              object.texts.map(fbb.writeString).toList(growable: false));
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.refId);
          fbb.addOffset(2, textsOffset);
          fbb.addInt64(3, object.character.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final textsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 8, []);
          final object = Dialog(refId: refIdParam, texts: textsParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.character.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.character.attach(store);
          return object;
        }),
    Faq: obx_int.EntityDefinition<Faq>(
        model: _entities[4],
        toOneRelations: (Faq object) => [object.chapter],
        toManyRelations: (Faq object) => {},
        getId: (Faq object) => object.id,
        setId: (Faq object, int id) {
          object.id = id;
        },
        objectToFB: (Faq object, fb.Builder fbb) {
          final questionOffset = fbb.writeString(object.question);
          final answerOffset = fbb.writeString(object.answer);
          final embeddingOffset = fbb.writeListFloat32(object.embedding);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.refId);
          fbb.addOffset(2, questionOffset);
          fbb.addOffset(3, answerOffset);
          fbb.addOffset(4, embeddingOffset);
          fbb.addInt64(5, object.chapter.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final questionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final answerParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final embeddingParam =
              const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                  .vTableGet(buffer, rootOffset, 12, []);
          final object = Faq(
              refId: refIdParam,
              question: questionParam,
              answer: answerParam,
              embedding: embeddingParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.chapter.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.chapter.attach(store);
          return object;
        }),
    Level: obx_int.EntityDefinition<Level>(
        model: _entities[5],
        toOneRelations: (Level object) => [object.chapter],
        toManyRelations: (Level object) => {},
        getId: (Level object) => object.id,
        setId: (Level object, int id) {
          object.id = id;
        },
        objectToFB: (Level object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final dataLevelOffset = fbb.writeString(object.dataLevel);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.refId);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(3, object.position);
          fbb.addOffset(4, dataLevelOffset);
          fbb.addBool(5, object.isCompleted);
          fbb.addInt64(6, object.chapter.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final positionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final dataLevelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final isCompletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final object = Level(
              refId: refIdParam,
              name: nameParam,
              position: positionParam,
              dataLevel: dataLevelParam,
              isCompleted: isCompletedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.chapter.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.chapter.attach(store);
          return object;
        }),
    Question: obx_int.EntityDefinition<Question>(
        model: _entities[6],
        toOneRelations: (Question object) => [object.type],
        toManyRelations: (Question object) => {},
        getId: (Question object) => object.id,
        setId: (Question object, int id) {
          object.id = id;
        },
        objectToFB: (Question object, fb.Builder fbb) {
          final descriptionOffset = fbb.writeString(object.description);
          final dataQuestionOffset = fbb.writeString(object.dataQuestion);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.refId);
          fbb.addOffset(2, descriptionOffset);
          fbb.addOffset(3, dataQuestionOffset);
          fbb.addInt64(4, object.type.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final dataQuestionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final object = Question(
              refId: refIdParam,
              description: descriptionParam,
              dataQuestion: dataQuestionParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.type.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.type.attach(store);
          return object;
        }),
    TypeQuestion: obx_int.EntityDefinition<TypeQuestion>(
        model: _entities[7],
        toOneRelations: (TypeQuestion object) => [],
        toManyRelations: (TypeQuestion object) => {},
        getId: (TypeQuestion object) => object.id,
        setId: (TypeQuestion object, int id) {
          object.id = id;
        },
        objectToFB: (TypeQuestion object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.refId);
          fbb.addOffset(2, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = TypeQuestion(refId: refIdParam, name: nameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Chapter] entity fields to define ObjectBox queries.
class Chapter_ {
  /// See [Chapter.id].
  static final id =
      obx.QueryIntegerProperty<Chapter>(_entities[0].properties[0]);

  /// See [Chapter.refId].
  static final refId =
      obx.QueryIntegerProperty<Chapter>(_entities[0].properties[1]);

  /// See [Chapter.name].
  static final name =
      obx.QueryStringProperty<Chapter>(_entities[0].properties[2]);

  /// See [Chapter.backgroundImgPath].
  static final backgroundImgPath =
      obx.QueryStringProperty<Chapter>(_entities[0].properties[3]);

  /// See [Chapter.iconImgPath].
  static final iconImgPath =
      obx.QueryStringProperty<Chapter>(_entities[0].properties[4]);

  /// See [Chapter.defaultDialogs].
  static final defaultDialogs =
      obx.QueryStringVectorProperty<Chapter>(_entities[0].properties[5]);

  /// See [Chapter.character].
  static final character =
      obx.QueryRelationToOne<Chapter, Character>(_entities[0].properties[6]);
}

/// [Character] entity fields to define ObjectBox queries.
class Character_ {
  /// See [Character.id].
  static final id =
      obx.QueryIntegerProperty<Character>(_entities[1].properties[0]);

  /// See [Character.refId].
  static final refId =
      obx.QueryIntegerProperty<Character>(_entities[1].properties[1]);

  /// See [Character.name].
  static final name =
      obx.QueryStringProperty<Character>(_entities[1].properties[2]);

  /// See [Character.pathImg].
  static final pathImg =
      obx.QueryStringProperty<Character>(_entities[1].properties[3]);
}

/// [Config] entity fields to define ObjectBox queries.
class Config_ {
  /// See [Config.id].
  static final id =
      obx.QueryIntegerProperty<Config>(_entities[2].properties[0]);

  /// See [Config.username].
  static final username =
      obx.QueryStringProperty<Config>(_entities[2].properties[1]);

  /// See [Config.insertedTables].
  static final insertedTables =
      obx.QueryBooleanProperty<Config>(_entities[2].properties[2]);
}

/// [Dialog] entity fields to define ObjectBox queries.
class Dialog_ {
  /// See [Dialog.id].
  static final id =
      obx.QueryIntegerProperty<Dialog>(_entities[3].properties[0]);

  /// See [Dialog.refId].
  static final refId =
      obx.QueryIntegerProperty<Dialog>(_entities[3].properties[1]);

  /// See [Dialog.texts].
  static final texts =
      obx.QueryStringVectorProperty<Dialog>(_entities[3].properties[2]);

  /// See [Dialog.character].
  static final character =
      obx.QueryRelationToOne<Dialog, Character>(_entities[3].properties[3]);
}

/// [Faq] entity fields to define ObjectBox queries.
class Faq_ {
  /// See [Faq.id].
  static final id = obx.QueryIntegerProperty<Faq>(_entities[4].properties[0]);

  /// See [Faq.refId].
  static final refId =
      obx.QueryIntegerProperty<Faq>(_entities[4].properties[1]);

  /// See [Faq.question].
  static final question =
      obx.QueryStringProperty<Faq>(_entities[4].properties[2]);

  /// See [Faq.answer].
  static final answer =
      obx.QueryStringProperty<Faq>(_entities[4].properties[3]);

  /// See [Faq.embedding].
  static final embedding =
      obx.QueryHnswProperty<Faq>(_entities[4].properties[4]);

  /// See [Faq.chapter].
  static final chapter =
      obx.QueryRelationToOne<Faq, Chapter>(_entities[4].properties[5]);
}

/// [Level] entity fields to define ObjectBox queries.
class Level_ {
  /// See [Level.id].
  static final id = obx.QueryIntegerProperty<Level>(_entities[5].properties[0]);

  /// See [Level.refId].
  static final refId =
      obx.QueryIntegerProperty<Level>(_entities[5].properties[1]);

  /// See [Level.name].
  static final name =
      obx.QueryStringProperty<Level>(_entities[5].properties[2]);

  /// See [Level.position].
  static final position =
      obx.QueryIntegerProperty<Level>(_entities[5].properties[3]);

  /// See [Level.dataLevel].
  static final dataLevel =
      obx.QueryStringProperty<Level>(_entities[5].properties[4]);

  /// See [Level.isCompleted].
  static final isCompleted =
      obx.QueryBooleanProperty<Level>(_entities[5].properties[5]);

  /// See [Level.chapter].
  static final chapter =
      obx.QueryRelationToOne<Level, Chapter>(_entities[5].properties[6]);
}

/// [Question] entity fields to define ObjectBox queries.
class Question_ {
  /// See [Question.id].
  static final id =
      obx.QueryIntegerProperty<Question>(_entities[6].properties[0]);

  /// See [Question.refId].
  static final refId =
      obx.QueryIntegerProperty<Question>(_entities[6].properties[1]);

  /// See [Question.description].
  static final description =
      obx.QueryStringProperty<Question>(_entities[6].properties[2]);

  /// See [Question.dataQuestion].
  static final dataQuestion =
      obx.QueryStringProperty<Question>(_entities[6].properties[3]);

  /// See [Question.type].
  static final type = obx.QueryRelationToOne<Question, TypeQuestion>(
      _entities[6].properties[4]);
}

/// [TypeQuestion] entity fields to define ObjectBox queries.
class TypeQuestion_ {
  /// See [TypeQuestion.id].
  static final id =
      obx.QueryIntegerProperty<TypeQuestion>(_entities[7].properties[0]);

  /// See [TypeQuestion.refId].
  static final refId =
      obx.QueryIntegerProperty<TypeQuestion>(_entities[7].properties[1]);

  /// See [TypeQuestion.name].
  static final name =
      obx.QueryStringProperty<TypeQuestion>(_entities[7].properties[2]);
}
